package br.com.gestaoservicos.orcamento.controller;
import br.com.gestaoservicos.compartilhado.paginacao.PaginaResponseDTO; import br.com.gestaoservicos.orcamento.dto.*; import br.com.gestaoservicos.orcamento.model.StatusOrcamento; import br.com.gestaoservicos.orcamento.service.OrcamentoService; import br.com.gestaoservicos.security.ContextoUnidade; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/orcamentos") public class OrcamentoController {
 private final OrcamentoService service; public OrcamentoController(OrcamentoService service){this.service=service;} private UUID unidade(){return ContextoUnidade.atual().orElseThrow().unidadeId();} private UUID usuario(){return UUID.fromString(SecurityContextHolder.getContext().getAuthentication().getName());}
 @GetMapping @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR','CONSULTA')") public PaginaResponseDTO<OrcamentoResponseDTO> listar(@RequestParam(required=false) String busca,@RequestParam(required=false) StatusOrcamento status,@PageableDefault(sort="numero") Pageable p){return service.listar(unidade(),busca,status,p);}
 @GetMapping("/{id}") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR','CONSULTA')") public OrcamentoResponseDTO consultar(@PathVariable UUID id){return service.consultar(unidade(),id);}
 @GetMapping("/{id}/revisoes/{numeroRevisao}/pdf") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR','CONSULTA')") public ResponseEntity<byte[]> baixarPdf(@PathVariable UUID id,@PathVariable int numeroRevisao){var pdf=service.baixarPdf(unidade(),id,numeroRevisao);return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(pdf.getNomeArquivo()).build().toString()).body(pdf.getConteudo());}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR')") public OrcamentoResponseDTO criar(@Valid @RequestBody OrcamentoRequestDTO dto){return service.criar(unidade(),dto,usuario());}
 @PutMapping("/{id}") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR')") public OrcamentoResponseDTO atualizar(@PathVariable UUID id,@Valid @RequestBody OrcamentoRequestDTO dto){return service.atualizar(unidade(),id,dto,usuario());}
 @PostMapping("/{id}/duplicar") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR')") public OrcamentoResponseDTO duplicar(@PathVariable UUID id){return service.duplicar(unidade(),id,usuario());}
 @PostMapping("/{id}/emitir") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR')") public OrcamentoResponseDTO emitir(@PathVariable UUID id,@Valid @RequestBody(required=false) TransicaoOrcamentoRequestDTO dto){return service.emitir(unidade(),id,dto==null?null:dto.observacao(),usuario());}
 @PostMapping("/{id}/nova-revisao") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR')") public OrcamentoResponseDTO novaRevisao(@PathVariable UUID id,@Valid @RequestBody(required=false) TransicaoOrcamentoRequestDTO dto){return service.novaRevisao(unidade(),id,dto==null?null:dto.observacao(),usuario());}
 @PostMapping("/{id}/aprovar") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR')") public OrcamentoResponseDTO aprovar(@PathVariable UUID id,@Valid @RequestBody(required=false) TransicaoOrcamentoRequestDTO dto){return service.transicionar(unidade(),id,StatusOrcamento.APROVADO,dto==null?null:dto.observacao(),usuario());}
 @PostMapping("/{id}/recusar") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR')") public OrcamentoResponseDTO recusar(@PathVariable UUID id,@Valid @RequestBody(required=false) TransicaoOrcamentoRequestDTO dto){return service.transicionar(unidade(),id,StatusOrcamento.RECUSADO,dto==null?null:dto.observacao(),usuario());}
 @PostMapping("/{id}/cancelar") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR')") public OrcamentoResponseDTO cancelar(@PathVariable UUID id,@Valid @RequestBody(required=false) TransicaoOrcamentoRequestDTO dto){return service.transicionar(unidade(),id,StatusOrcamento.CANCELADO,dto==null?null:dto.observacao(),usuario());}
 @PostMapping("/{id}/atualizacao-catalogo/previa") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR')") public AtualizacaoCatalogoPreviaResponseDTO previa(@PathVariable UUID id){return service.previaAtualizacaoCatalogo(unidade(),id);}
 @PostMapping("/{id}/atualizacao-catalogo/confirmar") @PreAuthorize("@autorizacaoUnidade.possuiAlgumPerfil('ADMIN','GESTOR','OPERADOR')") public OrcamentoResponseDTO confirmar(@PathVariable UUID id){return service.confirmarAtualizacaoCatalogo(unidade(),id,usuario());}
}
