package br.com.gestaoservicos.orcamento.service;

import br.com.gestaoservicos.catalogo.model.*;
import br.com.gestaoservicos.catalogo.repository.ItemCatalogoRepository;
import br.com.gestaoservicos.compartilhado.paginacao.PaginaResponseDTO;
import br.com.gestaoservicos.configuracaounidade.repository.ConfiguracaoUnidadeRepository;
import br.com.gestaoservicos.configuracaounidade.repository.FormaRecebimentoRepository;
import br.com.gestaoservicos.contratante.model.Contratante;
import br.com.gestaoservicos.contratante.repository.ContratanteRepository;
import br.com.gestaoservicos.orcamento.dto.*;
import br.com.gestaoservicos.orcamento.mapper.OrcamentoMapper;
import br.com.gestaoservicos.orcamento.model.*;
import br.com.gestaoservicos.orcamento.repository.*;
import br.com.gestaoservicos.unidade.repository.UnidadeRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.math.*; import java.time.*; import java.util.*;
import tools.jackson.databind.ObjectMapper;

@Service public class OrcamentoService {
 private final OrcamentoRepository orcamentos; private final RevisaoOrcamentoRepository revisoes; private final EventoOrcamentoRepository eventos; private final PdfOrcamentoRepository pdfs; private final UnidadeRepository unidades; private final ContratanteRepository contratantes; private final ItemCatalogoRepository catalogo; private final ConfiguracaoUnidadeRepository configuracoes; private final FormaRecebimentoRepository formasRecebimento; private final OrcamentoMapper mapper; private final JdbcTemplate jdbc; private final ObjectMapper json; private final GeradorPdfOrcamento geradorPdf;
 public OrcamentoService(OrcamentoRepository o,RevisaoOrcamentoRepository r,EventoOrcamentoRepository e,PdfOrcamentoRepository p,UnidadeRepository u,ContratanteRepository c,ItemCatalogoRepository i,ConfiguracaoUnidadeRepository conf,FormaRecebimentoRepository fr,OrcamentoMapper m,JdbcTemplate j,ObjectMapper json,GeradorPdfOrcamento g){orcamentos=o;revisoes=r;eventos=e;pdfs=p;unidades=u;contratantes=c;catalogo=i;configuracoes=conf;formasRecebimento=fr;mapper=m;jdbc=j;this.json=json;geradorPdf=g;}
 @Transactional(readOnly=true) public PaginaResponseDTO<OrcamentoResponseDTO> listar(UUID unidadeId,String busca,StatusOrcamento status,Pageable paginacao){return PaginaResponseDTO.de(orcamentos.buscar(unidadeId,limparOpcional(busca),status,paginacao).map(o->resposta(o)));}
 @Transactional(readOnly=true) public OrcamentoResponseDTO consultar(UUID unidadeId,UUID id){return resposta(obter(unidadeId,id));}
 @Transactional public OrcamentoResponseDTO criar(UUID unidadeId,OrcamentoRequestDTO dto,UUID usuario){var unidade=unidades.findById(unidadeId).orElseThrow(naoEncontrado("Unidade")); String numero=limparOpcional(dto.numero()); if(numero==null) numero=proximoNumero(unidadeId); validarNumero(unidadeId,numero,null); Orcamento o=orcamentos.save(new Orcamento(unidade,numero)); RevisaoOrcamento r=new RevisaoOrcamento(o,1); atualizarRevisao(unidadeId,r,comCondicoesPadrao(unidadeId,dto)); revisoes.save(r); evento(o,r,TipoEventoOrcamento.CRIADO,null,usuario); return resposta(o);}
 @Transactional public OrcamentoResponseDTO atualizar(UUID unidadeId,UUID id,OrcamentoRequestDTO dto,UUID usuario){Orcamento o=obter(unidadeId,id); if(o.getStatus()==StatusOrcamento.EMITIDO){if(br.com.gestaoservicos.security.ContextoUnidade.atual().orElseThrow().perfil()==br.com.gestaoservicos.associacao.model.Perfil.OPERADOR)throw new org.springframework.security.access.AccessDeniedException("Operador não pode criar revisão de orçamento emitido");novaRevisao(unidadeId,id,"Revisão criada para edição",usuario);} else exigirRascunho(o); if(dto.numero()!=null){if(o.isEmitidoInicialmente())throw conflito("O número não pode ser alterado após a primeira emissão");validarNumero(unidadeId,limpar(dto.numero()),o.getId());o.atualizarNumero(limpar(dto.numero()));} RevisaoOrcamento r=atual(o); atualizarRevisao(unidadeId,r,dto);evento(o,r,TipoEventoOrcamento.ATUALIZADO,null,usuario);return resposta(o);}
 @Transactional public OrcamentoResponseDTO duplicar(UUID unidadeId,UUID id,UUID usuario){Orcamento origem=obter(unidadeId,id); RevisaoOrcamento ro=atual(origem); Orcamento novo=orcamentos.save(new Orcamento(unidades.getReferenceById(unidadeId),proximoNumero(unidadeId))); RevisaoOrcamento rn=new RevisaoOrcamento(novo,1); copiar(ro,rn); revisoes.save(rn);evento(novo,rn,TipoEventoOrcamento.CRIADO,"Duplicado de "+origem.getNumero(),usuario);return resposta(novo);}
 @Transactional public OrcamentoResponseDTO emitir(UUID unidadeId,UUID id,String obs,UUID usuario){Orcamento o=obter(unidadeId,id); exigir(o,StatusOrcamento.RASCUNHO); RevisaoOrcamento r=atual(o); registrarSnapshots(unidadeId,r); pdfs.save(new PdfOrcamento(r,nomePdf(o,r),geradorPdf.gerar(o,r))); o.atualizarStatus(StatusOrcamento.EMITIDO);r.atualizarStatus(StatusOrcamento.EMITIDO);evento(o,r,TipoEventoOrcamento.EMITIDO,limparOpcional(obs),usuario);return resposta(o);}
 @Transactional public OrcamentoResponseDTO novaRevisao(UUID unidadeId,UUID id,String obs,UUID usuario){Orcamento o=obter(unidadeId,id); exigir(o,StatusOrcamento.EMITIDO); RevisaoOrcamento anterior=atual(o);o.avancarRevisao();RevisaoOrcamento nova=new RevisaoOrcamento(o,o.getRevisaoAtual());copiar(anterior,nova);revisoes.save(nova);evento(o,nova,TipoEventoOrcamento.REVISAO_CRIADA,limparOpcional(obs),usuario);return resposta(o);}
 @Transactional(readOnly=true) public PdfOrcamento baixarPdf(UUID unidadeId,UUID id,int numeroRevisao){Orcamento o=obter(unidadeId,id);RevisaoOrcamento r=revisoes.findByOrcamentoIdAndNumeroRevisao(o.getId(),numeroRevisao).orElseThrow(naoEncontrado("Revisao"));return pdfs.findByRevisaoId(r.getId()).orElseThrow(naoEncontrado("PDF da revisao"));}
 @Transactional public OrcamentoResponseDTO transicionar(UUID unidadeId,UUID id,StatusOrcamento destino,String obs,UUID usuario){Orcamento o=obter(unidadeId,id); StatusOrcamento origem=o.getStatus(); boolean permitido=(destino==StatusOrcamento.APROVADO||destino==StatusOrcamento.RECUSADO)&&origem==StatusOrcamento.EMITIDO || destino==StatusOrcamento.CANCELADO&&(origem==StatusOrcamento.RASCUNHO||origem==StatusOrcamento.EMITIDO);if(!permitido)throw conflito("Transição de status inválida");RevisaoOrcamento r=atual(o);o.atualizarStatus(destino);r.atualizarStatus(destino); evento(o,r, destino==StatusOrcamento.APROVADO?TipoEventoOrcamento.APROVADO:destino==StatusOrcamento.RECUSADO?TipoEventoOrcamento.RECUSADO:TipoEventoOrcamento.CANCELADO,limparOpcional(obs),usuario);return resposta(o);}
 @Transactional(readOnly=true) public AtualizacaoCatalogoPreviaResponseDTO previaAtualizacaoCatalogo(UUID unidadeId,UUID id){Orcamento o=obter(unidadeId,id);RevisaoOrcamento r=atual(o);List<MudancaValorCatalogoResponseDTO> mudancas=r.getItens().stream().filter(i->i.getItemCatalogo()!=null).filter(i->i.getValorUnitario().compareTo(i.getItemCatalogo().getValorPadrao())!=0).map(i->new MudancaValorCatalogoResponseDTO(i.getItemCatalogo().getId(),i.getDescricao(),i.getValorUnitario(),i.getItemCatalogo().getValorPadrao())).toList();return new AtualizacaoCatalogoPreviaResponseDTO(o.getId(),o.getStatus(),o.getStatus()==StatusOrcamento.EMITIDO,mudancas);}
 @Transactional public OrcamentoResponseDTO confirmarAtualizacaoCatalogo(UUID unidadeId,UUID id,UUID usuario){Orcamento o=obter(unidadeId,id);if(o.getStatus()==StatusOrcamento.EMITIDO){if(br.com.gestaoservicos.security.ContextoUnidade.atual().orElseThrow().perfil()==br.com.gestaoservicos.associacao.model.Perfil.OPERADOR)throw new org.springframework.security.access.AccessDeniedException("Operador não pode criar revisão de orçamento emitido");novaRevisao(unidadeId,id,"Revisão criada para atualizar valores pelo catálogo",usuario);} else exigirRascunho(o); RevisaoOrcamento r=atual(o); List<ItemRevisaoOrcamento> itens=new ArrayList<>();int ordem=1;for(ItemRevisaoOrcamento antigo:r.getItens()){ItemCatalogo c=antigo.getItemCatalogo();BigDecimal valor= c==null?antigo.getValorUnitario():c.getValorPadrao();itens.add(new ItemRevisaoOrcamento(r,ordem++,c,antigo.getTipo(),antigo.getDescricao(),antigo.getUnidadeMedida(),antigo.getUnidadeMedidaPersonalizada(),antigo.getQuantidade(),valor,antigo.getDesconto()));}r.removerItens();revisoes.saveAndFlush(r);r.atualizar(r.getContratante(),r.getValidade(),r.getCondicoesPagamento(),r.getObservacoesComerciais(),r.isExibirAssinatura(),r.getDescontoTipo(),r.getDescontoValor(),r.getAcrescimoTipo(),r.getAcrescimoValor(),itens);evento(o,r,TipoEventoOrcamento.VALORES_CATALOGO_ATUALIZADOS,null,usuario);return resposta(o);}
 private void atualizarRevisao(UUID unidadeId,RevisaoOrcamento r,OrcamentoRequestDTO dto){if(dto.descontoTipo()==TipoAjuste.PERCENTUAL&&dto.descontoValor().compareTo(new BigDecimal("100"))>0)throw conflito("Desconto percentual não pode ser maior que 100"); Contratante c=dto.contratanteId()==null?null:contratantes.findByIdAndUnidadeId(dto.contratanteId(),unidadeId).orElseThrow(naoEncontrado("Contratante")); if(!r.getItens().isEmpty()){r.removerItens();revisoes.saveAndFlush(r);} List<ItemRevisaoOrcamento> itens=new ArrayList<>();int ordem=1;for(ItemOrcamentoRequestDTO i:dto.itens())itens.add(criarItem(unidadeId,r,ordem++,i));r.atualizar(c,dto.validade(),limparOpcional(dto.condicoesPagamento()),limparOpcional(dto.observacoesComerciais()),dto.exibirAssinatura(),dto.descontoTipo(),dto.descontoValor(),dto.acrescimoTipo(),dto.acrescimoValor(),itens);if(r.getTotalFinal().signum()<0)throw conflito("O total final não pode ser negativo");}
 private void registrarSnapshots(UUID unidadeId, RevisaoOrcamento revisao) { var c=revisao.getContratante(); Map<String,Object> contratante=c==null?null:Map.of("id",c.getId(),"tipo",c.getTipo(),"nomeRazaoSocial",c.getNomeRazaoSocial(),"nomeFantasia",Objects.toString(c.getNomeFantasia(),""),"documento",c.getDocumento(),"endereco",Objects.toString(c.getEndereco(),""),"contatos",c.getContatos().stream().map(x->Map.of("nome",x.getNome(),"telefone",Objects.toString(x.getTelefone(),""),"email",Objects.toString(x.getEmail(),""))).toList()); var config=configuracoes.findByUnidadeId(unidadeId).orElse(null); Map<String,Object> contratado=config==null?Map.of():Map.of("nomeRazaoSocial",config.getNomeRazaoSocial(),"documento",config.getDocumento(),"enderecoCompleto",config.getEnderecoCompleto(),"nomeFantasia",Objects.toString(config.getNomeFantasia(),""),"email",Objects.toString(config.getEmail(),""),"logoUrl",Objects.toString(config.getLogoUrl(),"")); List<Map<String,Object>> pagamentos=config==null?List.of():formasRecebimento.findAllByConfiguracaoIdOrderByNomeExibicao(config.getId()).stream().filter(f->f.isAtiva()).map(f->Map.<String,Object>of("tipo",f.getTipo(),"nomeExibicao",f.getNomeExibicao(),"instrucoes",f.getInstrucoes(),"padrao",f.isPadrao())).toList(); revisao.registrarSnapshots(paraJson(contratante),paraJson(contratado),paraJson(pagamentos)); }
 private String paraJson(Object valor) { if(valor==null)return null; try{return json.writeValueAsString(valor);}catch(Exception e){throw new IllegalStateException("Nao foi possivel registrar snapshot da revisao",e);} }
 private OrcamentoRequestDTO comCondicoesPadrao(UUID unidadeId, OrcamentoRequestDTO dto){if(dto.condicoesPagamento()!=null&&!dto.condicoesPagamento().isBlank())return dto;String padrao=configuracoes.findByUnidadeId(unidadeId).map(c->c.getCondicoesPagamentoPadrao()).orElse(null);return new OrcamentoRequestDTO(dto.numero(),dto.contratanteId(),dto.validade(),padrao,dto.observacoesComerciais(),dto.exibirAssinatura(),dto.descontoTipo(),dto.descontoValor(),dto.acrescimoTipo(),dto.acrescimoValor(),dto.itens());}
 private ItemRevisaoOrcamento criarItem(UUID unidadeId,RevisaoOrcamento r,int ordem,ItemOrcamentoRequestDTO dto){ItemCatalogo c=null;TipoItemCatalogo tipo=dto.tipo();String descricao=dto.descricao();UnidadeMedida medida=dto.unidadeMedida();String personalizada=dto.unidadeMedidaPersonalizada();BigDecimal valor=dto.valorUnitario();if(dto.itemCatalogoId()!=null){c=catalogo.findByIdAndUnidadeId(dto.itemCatalogoId(),unidadeId).orElseThrow(naoEncontrado("Item de catálogo"));if(!c.isAtivo())throw conflito("Item de catálogo está inativo");tipo=c.getTipo();descricao=c.getDescricao()==null?c.getNome():c.getDescricao();medida=c.getUnidadeMedida();personalizada=c.getUnidadeMedidaPersonalizada();if(valor==null)valor=c.getValorPadrao();}else if(tipo==null||descricao==null||descricao.isBlank()||medida==null||valor==null)throw requisicao("Item manual deve informar tipo, descrição, unidade de medida e valor unitário");if(!medida.aceitaQuantidade(dto.quantidade()))throw requisicao("Quantidade inválida para a unidade de medida");if((medida==UnidadeMedida.OUTRA)!=(personalizada!=null&&!personalizada.isBlank()))throw requisicao("Unidade de medida personalizada inválida");return new ItemRevisaoOrcamento(r,ordem,c,tipo,limpar(descricao),medida,limparOpcional(personalizada),dto.quantidade(),valor);}
 private void copiar(RevisaoOrcamento origem,RevisaoOrcamento destino){List<ItemRevisaoOrcamento> itens=new ArrayList<>();int ordem=1;for(ItemRevisaoOrcamento i:origem.getItens())itens.add(new ItemRevisaoOrcamento(destino,ordem++,i.getItemCatalogo(),i.getTipo(),i.getDescricao(),i.getUnidadeMedida(),i.getUnidadeMedidaPersonalizada(),i.getQuantidade(),i.getValorUnitario(),i.getDesconto()));destino.atualizar(origem.getContratante(),origem.getValidade(),origem.getCondicoesPagamento(),origem.getObservacoesComerciais(),origem.isExibirAssinatura(),origem.getDescontoTipo(),origem.getDescontoValor(),origem.getAcrescimoTipo(),origem.getAcrescimoValor(),itens);}
 private String proximoNumero(UUID unidadeId){int ano=Year.now().getValue(); Long n; try { n=jdbc.queryForObject("insert into sequencia_orcamento (unidade_id, ano, proximo_numero) values (?, ?, 2) on conflict (unidade_id, ano) do update set proximo_numero = sequencia_orcamento.proximo_numero + 1 returning proximo_numero - 1",Long.class,unidadeId,ano); } catch (org.springframework.jdbc.BadSqlGrammarException bancoDeTeste) { n=proximoNumeroCompativel(unidadeId,ano); } return "ORC-%d-%06d".formatted(ano,n);}
 private synchronized Long proximoNumeroCompativel(UUID unidadeId,int ano){Long atual=jdbc.query("select proximo_numero from sequencia_orcamento where unidade_id=? and ano=?",rs->rs.next()?rs.getLong(1):null,unidadeId,ano);if(atual==null){try{jdbc.update("insert into sequencia_orcamento (unidade_id, ano, proximo_numero) values (?, ?, ?)",unidadeId,ano,2L);return 1L;}catch(org.springframework.dao.DuplicateKeyException ignorar){atual=jdbc.query("select proximo_numero from sequencia_orcamento where unidade_id=? and ano=?",rs->rs.next()?rs.getLong(1):null,unidadeId,ano);}}jdbc.update("update sequencia_orcamento set proximo_numero=? where unidade_id=? and ano=?",atual+1,unidadeId,ano);return atual;}
 private String nomePdf(Orcamento o,RevisaoOrcamento r){return o.getNumero()+"-rev-"+r.getNumeroRevisao()+".pdf";} private Orcamento obter(UUID unidadeId,UUID id){return orcamentos.findByIdAndUnidadeId(id,unidadeId).orElseThrow(naoEncontrado("Orçamento"));} private RevisaoOrcamento atual(Orcamento o){return revisoes.findByOrcamentoIdAndNumeroRevisao(o.getId(),o.getRevisaoAtual()).orElseThrow(()->new IllegalStateException("Revisão atual ausente"));} private OrcamentoResponseDTO resposta(Orcamento o){RevisaoOrcamento r=atual(o);return mapper.paraOrcamento(o,r,revisoes.findAllByOrcamentoIdOrderByNumeroRevisaoDesc(o.getId()),eventos.findAllByOrcamentoIdOrderByOcorridoEmDesc(o.getId()));} private void evento(Orcamento o,RevisaoOrcamento r,TipoEventoOrcamento t,String obs,UUID usuario){eventos.save(new EventoOrcamento(o,r,t,obs,usuario));} private void exigirRascunho(Orcamento o){exigir(o,StatusOrcamento.RASCUNHO);} private void exigir(Orcamento o,StatusOrcamento s){if(o.getStatus()!=s)throw conflito("Ação permitida apenas para orçamento em "+s);} private void validarNumero(UUID u,String n,UUID id){if(n==null||n.isBlank())throw requisicao("Número do orçamento é obrigatório");boolean existe=id==null?orcamentos.existsByUnidadeIdAndNumero(u,n):orcamentos.existsByUnidadeIdAndNumeroAndIdNot(u,n,id);if(existe)throw conflito("Número de orçamento já existe na unidade");} private java.util.function.Supplier<ResponseStatusException> naoEncontrado(String t){return ()->new ResponseStatusException(HttpStatus.NOT_FOUND,t+" não encontrado");} private ResponseStatusException conflito(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);} private ResponseStatusException requisicao(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private String limpar(String s){return s.strip().replaceAll("\\s+"," ");} private String limparOpcional(String s){return s==null||s.isBlank()?null:limpar(s);}
}
