package br.com.gestaoservicos.empresa.service;
import br.com.gestaoservicos.empresa.dto.*; import br.com.gestaoservicos.empresa.model.*; import br.com.gestaoservicos.empresa.repository.EmpresaRepository; import br.com.gestaoservicos.unidade.repository.UnidadeRepository; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class EmpresaService { private final EmpresaRepository empresas; private final UnidadeRepository unidades; public EmpresaService(EmpresaRepository e, UnidadeRepository u){empresas=e;unidades=u;}
 @Transactional(readOnly=true) public List<EmpresaResponseDTO> listar(UUID unidade){return empresas.findByUnidadeIdOrderByRazaoSocial(unidade).stream().map(this::dto).toList();}
 @Transactional public EmpresaResponseDTO criar(UUID unidade, EmpresaRequestDTO r){validar(unidade,r,null); var u=unidades.findById(unidade).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND)); var e=new Empresa(u,matriz(unidade,r),r.tipo(),r.razaoSocial().strip(),limpar(r.nomeFantasia()),r.cnpj(),limpar(r.inscricaoEstadual()),limpar(r.telefone()),limpar(r.email()),limpar(r.cep()),limpar(r.logradouro()),limpar(r.numero()),limpar(r.complemento()),limpar(r.bairro()),limpar(r.cidade()),limpar(r.estado()));e.atualizarLogo(limpar(r.logoUrl()));return dto(empresas.save(e));}
 @Transactional public EmpresaResponseDTO atualizar(UUID unidade,UUID id,EmpresaRequestDTO r){var e=obter(unidade,id);validar(unidade,r,id);e.atualizar(matriz(unidade,r),r.tipo(),r.razaoSocial().strip(),limpar(r.nomeFantasia()),r.cnpj(),limpar(r.inscricaoEstadual()),limpar(r.telefone()),limpar(r.email()),limpar(r.cep()),limpar(r.logradouro()),limpar(r.numero()),limpar(r.complemento()),limpar(r.bairro()),limpar(r.cidade()),limpar(r.estado()));e.atualizarLogo(limpar(r.logoUrl()));return dto(e);}
 @Transactional public EmpresaResponseDTO status(UUID unidade,UUID id,boolean ativa){var e=obter(unidade,id);if(ativa)e.reativar();else e.inativar();return dto(e);} private Empresa obter(UUID u,UUID id){return empresas.findByIdAndUnidadeId(id,u).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Empresa não encontrada"));} private Empresa matriz(UUID u,EmpresaRequestDTO r){if(r.tipo()==TipoEmpresa.MATRIZ)return null;if(r.matrizId()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe a matriz da filial");var e=obter(u,r.matrizId());if(e.getTipo()!=TipoEmpresa.MATRIZ)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"A empresa selecionada não é matriz");return e;} private void validar(UUID u,EmpresaRequestDTO r,UUID id){validarLogo(r.logoUrl());boolean existe=id==null?empresas.existsByUnidadeIdAndCnpj(u,r.cnpj()):empresas.existsByUnidadeIdAndCnpjAndIdNot(u,r.cnpj(),id);if(existe)throw new ResponseStatusException(HttpStatus.CONFLICT,"Já existe uma empresa com este CNPJ");} private void validarLogo(String logo){
 if(logo==null)return;
 try{
   if(logo.length()>700000||!logo.matches("data:image/(png|jpeg);base64,[A-Za-z0-9+/=]+"))throw new IllegalArgumentException();
   byte[] bytes=Base64.getDecoder().decode(logo.substring(logo.indexOf(',')+1));
   try(var entrada=javax.imageio.ImageIO.createImageInputStream(new java.io.ByteArrayInputStream(bytes))){
     var leitores=javax.imageio.ImageIO.getImageReaders(entrada);if(!leitores.hasNext())throw new IllegalArgumentException();
     var leitor=leitores.next();try{leitor.setInput(entrada);String formato=leitor.getFormatName();if(!formato.equalsIgnoreCase("png")&&!formato.equalsIgnoreCase("jpeg"))throw new IllegalArgumentException();
       int largura=leitor.getWidth(0),altura=leitor.getHeight(0);if(largura<=0||altura<=0||largura>4000||altura>4000)throw new IllegalArgumentException();
     }finally{leitor.dispose();}
   }
 }catch(Exception ex){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Logo inválida. Envie uma imagem PNG ou JPG de até 4000 pixels.");}
 }
 private String limpar(String s){return s==null||s.isBlank()?null:s.strip();} private EmpresaResponseDTO dto(Empresa e){return new EmpresaResponseDTO(e.getId(),e.getTipo(),e.getMatriz()==null?null:e.getMatriz().getId(),e.getMatriz()==null?null:e.getMatriz().getRazaoSocial(),e.getRazaoSocial(),e.getNomeFantasia(),e.getCnpj(),e.getInscricaoEstadual(),e.getTelefone(),e.getEmail(),e.getCep(),e.getLogradouro(),e.getNumero(),e.getComplemento(),e.getBairro(),e.getCidade(),e.getEstado(),e.isAtivo(),e.getLogoUrl());}}
