package br.com.gestaoservicos.convite.service;
import br.com.gestaoservicos.associacao.model.*; import br.com.gestaoservicos.associacao.repository.AssociacaoRepository; import br.com.gestaoservicos.config.*; import br.com.gestaoservicos.convite.dto.*; import br.com.gestaoservicos.convite.model.*; import br.com.gestaoservicos.convite.repository.*; import br.com.gestaoservicos.unidade.repository.UnidadeRepository; import br.com.gestaoservicos.usuario.repository.UsuarioRepository;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@Service public class ConviteUnidadeService {
 private final ConviteUnidadeRepository convites; private final UnidadeRepository unidades; private final UsuarioRepository usuarios; private final AssociacaoRepository associacoes; private final SecureRandom aleatorio=new SecureRandom();
 public ConviteUnidadeService(ConviteUnidadeRepository c,UnidadeRepository u,UsuarioRepository us,AssociacaoRepository a){convites=c;unidades=u;usuarios=us;associacoes=a;}
 @Transactional public ConviteUnidadeResponseDTO criar(UUID unidadeId,String email,Perfil perfil){var unidade=unidades.findById(unidadeId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Unidade não encontrada"));String codigo=gerarCodigo();var convite=convites.save(new ConviteUnidade(unidade,email.trim().toLowerCase(Locale.ROOT),perfil,hash(codigo),Instant.now().plus(7,ChronoUnit.DAYS)));return ConviteUnidadeResponseDTO.de(convite,codigo);}
 @Transactional(readOnly=true) public List<ConviteUnidadeResponseDTO> listar(UUID unidadeId){return convites.findAllByUnidadeIdOrderByExpiraEmDesc(unidadeId).stream().map(c->ConviteUnidadeResponseDTO.de(c,null)).toList();}
 @Transactional public void revogar(UUID unidadeId,UUID conviteId){var convite=convites.findByIdAndUnidadeId(conviteId,unidadeId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Convite não encontrado")); if(!convite.estaDisponivel()) throw new ResponseStatusException(HttpStatus.CONFLICT,"Este convite não está mais disponível"); convite.revogar();}
 @Transactional public void aceitar(UUID usuarioId,String codigo){var convite=convites.findByTokenHash(hash(codigo)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Convite inválido"));if(!convite.estaDisponivel()) throw new ResponseStatusException(HttpStatus.CONFLICT,"Este convite não está mais disponível");var usuario=usuarios.findById(usuarioId).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Usuário não encontrado"));if(!usuario.getEmail().equalsIgnoreCase(convite.getEmail()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Este convite foi emitido para outro e-mail");if(associacoes.existsByUsuarioIdAndUnidadeIdAndAtivaTrue(usuarioId,convite.getUnidade().getId()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Você já possui acesso a esta unidade");associacoes.save(new Associacao(usuario,convite.getUnidade(),convite.getPerfil()));convite.aceitar();}
 private String gerarCodigo(){byte[] bytes=new byte[24];aleatorio.nextBytes(bytes);return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);} private String hash(String texto){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(texto.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
