package br.com.gestaoservicos.orcamento.model;
import br.com.gestaoservicos.catalogo.model.*;
import jakarta.persistence.*;
import java.math.*; import java.util.UUID;
@Entity @Table(name="item_revisao_orcamento") public class ItemRevisaoOrcamento {
 @Id private UUID id; @ManyToOne(fetch=FetchType.LAZY, optional=false) @JoinColumn(name="revisao_orcamento_id") private RevisaoOrcamento revisao; private int ordem; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="item_catalogo_id") private ItemCatalogo itemCatalogo; @Enumerated(EnumType.STRING) @Column(nullable=false) private TipoItemCatalogo tipo; @Column(nullable=false) private String descricao; @Enumerated(EnumType.STRING) @Column(name="unidade_medida",nullable=false) private UnidadeMedida unidadeMedida; @Column(name="unidade_medida_personalizada") private String unidadeMedidaPersonalizada; @Column(nullable=false,precision=15,scale=2) private BigDecimal quantidade; @Column(name="valor_unitario",nullable=false,precision=15,scale=2) private BigDecimal valorUnitario; @Column(nullable=false,precision=15,scale=2) private BigDecimal desconto=BigDecimal.ZERO; @Column(nullable=false,precision=15,scale=2) private BigDecimal total;
 protected ItemRevisaoOrcamento(){} public ItemRevisaoOrcamento(RevisaoOrcamento r,int ordem,ItemCatalogo c,TipoItemCatalogo t,String d,UnidadeMedida u,String up,BigDecimal q,BigDecimal v){this(r,ordem,c,t,d,u,up,q,v,BigDecimal.ZERO);} public ItemRevisaoOrcamento(RevisaoOrcamento r,int ordem,ItemCatalogo c,TipoItemCatalogo t,String d,UnidadeMedida u,String up,BigDecimal q,BigDecimal v,BigDecimal desconto){id=UUID.randomUUID();revisao=r;this.ordem=ordem;itemCatalogo=c;tipo=t;descricao=d;unidadeMedida=u;unidadeMedidaPersonalizada=up;quantidade=q;valorUnitario=v;this.desconto=desconto;total=q.multiply(v).subtract(desconto).setScale(2,RoundingMode.HALF_UP);}
 public ItemCatalogo getItemCatalogo(){return itemCatalogo;} public TipoItemCatalogo getTipo(){return tipo;} public String getDescricao(){return descricao;} public UnidadeMedida getUnidadeMedida(){return unidadeMedida;} public String getUnidadeMedidaPersonalizada(){return unidadeMedidaPersonalizada;} public BigDecimal getQuantidade(){return quantidade;} public BigDecimal getValorUnitario(){return valorUnitario;} public BigDecimal getDesconto(){return desconto;} public BigDecimal getTotal(){return total;}
}
