create table servico (
    id uuid primary key,
    unidade_id uuid not null references unidade(id),
    contratante_id uuid not null references contratante(id),
    orcamento_id uuid references orcamento(id),
    codigo varchar(30) not null,
    titulo varchar(200) not null,
    categoria varchar(100),
    descricao varchar(4000),
    responsavel varchar(120),
    equipe varchar(120),
    local_execucao varchar(500),
    inicio_previsto timestamp with time zone,
    fim_previsto timestamp with time zone,
    concluido_em timestamp with time zone,
    resumo_conclusao varchar(4000),
    status varchar(30) not null,
    versao bigint not null default 0,
    criado_em timestamp with time zone not null,
    atualizado_em timestamp with time zone not null,
    criado_por uuid,
    atualizado_por uuid,
    constraint uk_servico_codigo unique (unidade_id, codigo),
    constraint ck_servico_status check (status in ('RASCUNHO','AGENDADO','EM_ANDAMENTO','AGUARDANDO','CONCLUIDO','CANCELADO'))
);
create index ix_servico_unidade_inicio on servico(unidade_id, inicio_previsto);

create table despesa (
    id uuid primary key,
    unidade_id uuid not null references unidade(id),
    servico_id uuid references servico(id),
    orcamento_id uuid references orcamento(id),
    codigo varchar(30) not null,
    categoria varchar(100) not null,
    descricao varchar(500) not null,
    valor numeric(15,2) not null,
    data_despesa date not null,
    responsavel varchar(120),
    comprovante_url varchar(1000),
    status varchar(20) not null,
    comentario_decisao varchar(2000),
    decidido_em timestamp with time zone,
    decidido_por uuid,
    versao bigint not null default 0,
    criado_em timestamp with time zone not null,
    atualizado_em timestamp with time zone not null,
    criado_por uuid,
    atualizado_por uuid,
    constraint uk_despesa_codigo unique (unidade_id, codigo),
    constraint ck_despesa_status check (status in ('RASCUNHO','PENDENTE','APROVADA','REJEITADA','CANCELADA')),
    constraint ck_despesa_valor check (valor > 0)
);
create index ix_despesa_unidade_data on despesa(unidade_id, data_despesa);

create table contrato (
    id uuid primary key,
    unidade_id uuid not null references unidade(id),
    contratante_id uuid not null references contratante(id),
    orcamento_id uuid not null references orcamento(id),
    numero varchar(30) not null,
    modelo varchar(120) not null,
    objeto varchar(4000) not null,
    clausulas_adicionais varchar(8000),
    inicio_vigencia date not null,
    fim_vigencia date not null,
    valor_total numeric(15,2) not null,
    condicoes_pagamento varchar(2000),
    status varchar(30) not null,
    numero_versao integer not null,
    assinado_por varchar(120),
    assinado_em date,
    canal_assinatura varchar(120),
    evidencia_url varchar(1000),
    versao bigint not null default 0,
    criado_em timestamp with time zone not null,
    atualizado_em timestamp with time zone not null,
    criado_por uuid,
    atualizado_por uuid,
    constraint uk_contrato_numero unique (unidade_id, numero),
    constraint uk_contrato_orcamento unique (orcamento_id),
    constraint ck_contrato_status check (status in ('RASCUNHO','AGUARDANDO_ASSINATURA','ATIVO','ENCERRADO','CANCELADO'))
);
create index ix_contrato_unidade_fim on contrato(unidade_id, fim_vigencia);
